spryk: method
description: "Adds a new method to the Resource Mapper Interface."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    resourceType:
        inherit: true

    fromTransfer:
        inherit: true
        default: "Rest{{ resourceType | dashToCamelCase }}AttributesTransfer"

    toTransfer:
        inherit: true
        default: "Rest{{ resourceType | dashToCamelCase }}AttributesTransfer"

    method:
        value: "map{{ fromTransfer }}To{{ toTransfer }}"
        inherit: true

    template:
        value: Glue/Processor/Mapper/GlueResourceMapperInterfaceMethod.php.twig

    target:
        value: "{{ organization }}\\Glue\\{{ module }}\\Processor\\Mapper\\{{ resourceType | singularize | dashToCamelCase}}MapperInterface"

preSpryks:
    - AddModule
    - AddSharedRestAttributesTransfer:
        arguments:
            name:
                value: "{{ resourceType | dashToCamelCase }}"
                callback:
                    - EnsureRestAttributesTransferAffix
    - AddGlueResourceMapperInterface:
        arguments:
            className:
                value: "{{ resourceType | singularize | dashToCamelCase }}Mapper"
            subDirectory:
                value: "Mapper"
