spryk: method
description: "Adds a Client dependency method to the *module*Factory."
mode: both

arguments:
    module:
        inherit: true

    dependentModule:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    factoryMethod:
        value: "get{{ dependentModule }}Client"

    template:
        value: Glue/Dependency/Client/GlueDependencyClientFactoryMethod.php.twig

    target:
        value: "{{ organization }}\\Glue\\{{ module }}\\{{ module }}Factory"

preSpryks:
    - AddGlueFactory

postSpryks:
    - AddGlueDependencyClientDependencyProviderConstant:
        arguments:
            name:
                value: "CLIENT_{{ dependentModule | underscored | upper }}"
            value:
                value: "CLIENT_{{ dependentModule | underscored | upper }}"
            visibility:
                value: "public"

