build:
    environment:
        php: '7.3'

    tests:
        override:
            - true

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

build_failure_conditions:
    - 'project.metric("scrutinizer.quality", < 10)'

checks:
    php:
        code_rating: true
        duplication: true
