# Adds a MessageHandler class
# Adds a MessageHandler interface
# Adds the Factory method to get the MessageHandler
# Adds a facade method to call the created handler
spryk: template
description: "Adds a new MessageBroker MessageHandler to the Zed application."
mode: both
level: 2

application: Zed
layer: Business

priority: 1

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    messageName:
        inherit: true

    className:
        value: "{{ module }}MessageHandler"

    subDirectory:
        inherit: true
        value: "MessageBroker"

    interfaceName:
        value: "\\{{ organization}}\\Zed\\{{ module}}\\Business\\MessageBroker\\{{ className }}Interface"

    template:
        value: Zed/Business/MessageBroker/MessageHandler.php.twig

    targetFilename:
        callbackOnly: true
        callback: ZedBusinessModelTargetFilenameCallback

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Business"

preSpryks:
    - AddModule

postSpryks:
    - AddZedBusinessModelInterface # Add Interface for the newly created method
    - AddZedBusinessFactoryMethod: # Add method to get the MessageBrokerFacade dependency for class creation in the factory
          arguments:
              subDirectory:
                  value: "MessageBroker"
              dependencyMethods:
                  value:
                      - "getMessageBrokerFacade"

    - AddZedBusinessFactoryDependencyMethod:
          arguments:
              dependencyType:
                  value: "Facade"
              dependentModule:
                  value: "MessageBroker"
              dependencyMethod:
                  value: "getMessageBrokerFacade"

    - AddZedDependencyFacadeDependencyProviderMethod:
          arguments:
              dependentModule:
                  value: "MessageBroker"
