spryk: method
description: "Adds a new method to the *target* processor model."
mode: both

application: Glue

priority: 1

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    className:
        inherit: true

    subDirectory:
        inherit: true
        isOptional: true

    method:
        inherit: true

    input:
        isOptional: true
        isMultiple: true

    output:
        isOptional: true

    template:
        value: Common/Method.php.twig

    target:
        value: '{{ organization }}\Glue\{{ module }}\Processor{% if subDirectory %}\{{ subDirectory }}{% endif %}\{{ className }}'

preSpryks:
    - AddGlueProcessorModel

postSpryks:
    - AddGlueProcessorModelInterfaceMethod
