spryk: constant
description: "Adds a constant to the target class."
mode: both

arguments:
    organization:
        inherit: true
        default: SprykerShop

    module:
        inherit: true

    name: ~
    value: ~
    visibility:
        value: "protected"

    target: ~

