spryk: method
description: "Adds a new action to the Yves controller."
mode: both

arguments:
    organization:
        inherit: true
        default: SprykerShop

    module:
        inherit: true

    controller:
        inherit: true
        callback:
            - ClassNameShortCallback
            - EnsureControllerSuffixCallback
        type: ClassNameChoice
        choiceLoader: ZedCommunicationControllerChoiceLoader
        typeOptions:
            - module
            - existingModule
            - spryk
            - choiceLoader

    controllerMethod:
        inherit: true
        callback: EnsureActionSuffixCallback

    theme:
        inherit: true
        default: default

    constantName:
        value: "ROUTE_{{ controller | classNameShort | removeControllerSuffix | underscored | upper }}_{{ controllerMethod | removeActionSuffix | underscored | upper }}"

    templateName:
        value: "{{ controllerMethod | removeActionSuffix | dasherize }}"

    template:
        value: Yves/RouteProvider/YvesRouteProviderMethod.php.twig

    target:
        value: "{{ organization }}\\Yves\\{{ module }}\\Plugin\\Router\\{{ module }}RouteProviderPlugin"

preSpryks:
    - AddYvesControllerAction
    - AddYvesRouteProvider
    - AddConstant:
        arguments:
            name:
                value: "{{ constantName }}"
            value:
                value: "{{ module | dasherize }}/{{ controller | removeControllerSuffix | dasherize }}-{{ controllerMethod | removeActionSuffix | dasherize }}"
            visibility:
                value: "protected"
            target:
                value: "{{ organization }}\\Yves\\{{ module }}\\Plugin\\Router\\{{ module }}RouteProviderPlugin"


