spryk: method
description: "Adds a new method to the *target* business model in Data import ."
mode: both

application: Zed
layer: Business

priority: 1

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true

    subDirectory:
        inherit: true
        isOptional: true

    className:
        inherit: true
        type: ClassNameChoice
        choiceLoader: ZedBusinessModelChoiceLoader
        typeOptions:
            - module
            - existingModule
            - spryk
            - choiceLoader

    modelMethod:
        inherit: true

    input:
        inherit: true
        isOptional: true

    output:
        inherit: true
        isOptional: true

    template:
        value: Common/Method.php.twig

    target:
        value: "{{ className }}"

    fqcnPattern:
        value: "{{ organization }}\\Zed\\{{ module }}\\Business\\{{ subDirectory | convertToClassNameFragment }}\\{{ className }}"

preSpryks:
    - AddDataImportZedBusinessWriterStep
