spryk: template
description: "Adds a new DomainEntity related interface to the Zed application."
mode: both
level: 2

application: Zed

priority: 1

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    layer:
        inherit: true
        default: Business

    extends:
        inherit: true
        isMultiple: true
        isOptional: true

    subDirectory:
        inherit: true
        isOptional: true

    className:
        inherit: true

    interfaceName:
        value: "{{ className }}Interface"

    template:
        value: Common/ModelInterface.php.twig

    targetFilename:
        value: "{{ interfaceName }}.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/{{ layer }}"
preSpryks:
    - AddModule
