spryk: method
description: "Adds a method to the *module*BusinessFactory."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    subDirectory:
        inherit: true
        isOptional: true

    className:
        inherit: true

    interfaceName:
        inherit: true
        isOptional: true

    factoryMethod:
        callbackOnly: true
        callback: ZedBusinessFactoryMethodNameCallback

    dependencyMethods:
        isMultiple: true
        isOptional: true

    body:
        value: ""

    template:
        value: Zed/Business/MethodBusinessFactory.php.twig

    target:
        value: "{{ organization }}\\Zed\\{{ module }}\\Business\\{{ module }}BusinessFactory"

preSpryks:
    - AddZedBusinessFactory
