spryk: template
description: "Adds a new *module*FacadeTest."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: Zed/Business/ZedBusinessFacadeTest.php.twig

    targetFilename:
        value: "{{ module }}FacadeTest.php"

    targetPath:
        value: "{{ moduleRoot }}/tests/{{ organization }}Test/Zed/{{ module }}/Business/"

preSpryks:
    - AddZedBusinessTestSuite
