spryk: bridgeMethods
description: "Adds a new method to the *module* dependency Client bridge."
mode: core

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true

    dependentModuleOrganization:
        inherit: true
        default: Spryker

    dependentModule:
        inherit: true

    methods:
        type: MethodNameChoice
        choiceLoader: ClientMethodChoiceLoader
        isMultiple: true
        typeOptions:
            - module
            - choiceLoader

    template:
        value: Client/Dependency/ClientDependencyBridgeInterfaceMethod.php.twig

    dependencyType:
        value: Client

    sourceClass:
        value: "{{ dependentModuleOrganization }}\\Client\\{{ dependentModule }}\\{{ dependentModule }}ClientInterface"

    target:
        value: "{{ organization }}\\Client\\{{ module }}\\Dependency\\Client\\{{ module }}To{{ dependentModule }}ClientInterface"

preSpryks:
    - AddClientDependencyClientInterface

postSpryks:
    - AddClientDependencyClientBridgeMethod
