spryk: method
description: "Adds a new method to the Zed *module*Config."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    configMethod: ~
    input: ~
    output: ~

    template:
        value: Common/Method.php.twig

    target:
        value: "{{ organization }}\\Zed\\{{ module }}\\{{ module }}Config"

preSpryks:
    - AddZedConfig

