spryk: template
description: "Adds a new *module* class."
mode: both

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  className: ~

  implementerInterfaceName:
    isOptional: true

  expanderClassName:
    isOptional: true

  subDirectory: ~

  template:
    value: Common/Class.php.twig

  targetFilename:
    value: "{{ className }}.php"

  targetPath:
    value: "{{ module }}/src/{{ organization }}/"
