spryk: template
description: "Adds a new .coveralls.yml to the Modules root."
mode: core

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true

    template:
        value: coveralls.yml.twig

    targetFilename:
        value: .coveralls.yml

    targetPath:
        value: "{{ module }}/"

preSpryks:
    - AddModule
