spryk: template
description: "Adds a new composer.json to the Modules root."
mode: core

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: composer.json.twig

    targetPath:
        value: "{{ module }}/"

preSpryks:
    - AddModule

postCommands:
    - ComposerReplaceGenerate
    - ComposerDumpAutoload
