spryk: structure
description: "Adds a new *module* Yves structure."
priority: 1
mode: both
level: 1

arguments:
    organization:
        inherit: true
        default: SprykerShop

    module:
        inherit: true
        type: NewModuleType

    targetPath:
        value: "{{ moduleRoot }}/"

    directories:
        value:
            - "src/{{ organization }}/"

postSpryks:
    - AddModule
    - AddSharedTransferSchema
    - AddYvesFactory
    - AddYvesDependencyProvider
    - AddYvesConfig
    - AddYvesTheme
