spryk: copyModule
description: "Copies a *module*."
priority: 1
mode: core
level: 1

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    toModule:
        inherit: true

    toOrganization:
        inherit: true
        default: Spryker

    sourcePath:
        value: "vendor/{{ sprykerVendorPath }}{{ organization | dasherize }}/{{ moduleSrcDirectory }}{{ moduleRoot }}/"

    targetFilePath:
        value: "vendor/{{ sprykerVendorPath }}{{ toOrganization | dasherize }}/{{ moduleSrcDirectory }}{{ toModule }}/"

postCommands:
    - ComposerReplaceGenerate
    - ComposerDumpAutoload
