spryk: method
description: "Adds a new method to the *module*RepositoryInterface."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    repositoryMethod:
        inherit: true

    input:
        inherit: true

    output:
        inherit: true


    template:
        value: Common/InterfaceMethod.php.twig

    target:
        value: "{{ organization }}\\Zed\\{{ module }}\\Persistence\\{{ module }}RepositoryInterface"

preSpryks:
    - AddZedPersistenceRepositoryInterface
