spryk: bridgeMethods
description: "Adds a new method to the *module* dependency Service bridge interface."
mode: core

arguments:
    module:
        inherit: true
        moduleFilter:
            application: Zed

    organization:
        inherit: true
        default: Spryker

    dependentModule:
        inherit: true
        moduleFilter:
            application: Service

    methods:
        type: MethodNameChoice
        choiceLoader: ServiceMethodChoiceLoader
        isMultiple: true
        typeOptions:
            - module
            - choiceLoader

    template:
        value: Zed/Dependency/ZedDependencyBridgeInterfaceMethod.php.twig

    dependencyType:
        value: Service

    sourceClass:
        value: "{{ organization }}\\Service\\{{ dependentModule }}\\{{ dependentModule }}ServiceInterface"

    target:
        value: "{{ organization }}\\Zed\\{{ module }}\\Dependency\\Service\\{{ module }}To{{ dependentModule }}ServiceInterface"

preSpryks:
    - AddZedDependencyServiceInterface

postSpryks:
    - AddZedDependencyServiceBridgeMethod


