spryk: method
description: "Adds a Service dependency method to the *module*BusinessFactory."
mode: both

arguments:
  module:
    moduleFilter:
      application: Zed

  dependentModule:
    inherit: true
    moduleFilter:
      application: Service

  organization:
    inherit: true
    default: Spryker

  factoryMethod:
    value: "get{{ dependentModule }}Service"

  template:
    value: Zed/Dependency/Service/ZedDependencyServiceBusinessFactoryMethod.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ module }}\\Business\\{{ module }}BusinessFactory"

preSpryks:
  - AddZedBusinessFactory

postSpryks:
  - AddZedDependencyServiceDependencyProviderConstant:
      arguments:
        name:
          value: "SERVICE_{{ dependentModule | underscored | upper }}"
        value:
          value:  "{{ dependentModule | camelCaseToWhitespace | lower }} service"
        visibility:
          value:  "public"
