spryk: method
description: "Adds a new Interface method to the *Module*ClientInterface."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    clientMethod:
        inherit: true

    input:
        inherit: true

    output:
        inherit: true


    specification:
        multiline: true

    template:
        value: Common/InterfaceMethod.php.twig

    target:
        value: "{{ organization }}\\Client\\{{ module }}\\{{ module }}ClientInterface"

preSpryks:
    - AddClientInterface
