spryk: method
description: "Adds a new action to the Glue controller."
mode: both
level: 2

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    controller:
        callback:
            - ClassNameShortCallback
            - EnsureControllerSuffixCallback

    controllerMethod:
        default: "patchAction"
        callback: EnsureActionSuffixCallback

    resourceType:
        inherit: true

    modelName:
        value: "{{ resourceType | dashToCamelCase | singularize }}"

    modelSuffix:
        inherit: true
        default: "Updater"

    template:
        value: Glue/Controller/MethodPatchGlueController.php.twig

    target:
        value: "{{ organization }}\\Glue\\{{ module }}\\Controller\\{{ controller | classNameShort | ensureControllerSuffix }}"

preSpryks:
    - AddGlueController
    - AddGlueProcessorModelMethod:
        arguments:
            className:
                value: "{{ modelName }}{{ modelSuffix }}"
            input:
                value: "\\Spryker\\Glue\\GlueApplication\\Rest\\Request\\Data\\RestRequestInterface $restRequest"
            output:
                value: "\\Spryker\\Glue\\GlueApplication\\Rest\\JsonApi\\RestResponseInterface"
            method:
                value: "update{{ modelName }}"
            subDirectory:
                value: "{{ modelName }}"
