spryk: constant
description: "Adds a Client dependency constant to the *module*DependencyProvider."
mode: both

arguments:
    organization:
        inherit: true
        default: SprykerShop

    module:
        inherit: true

    dependentModule:
        inherit: true

    name: ~
    value: ~
    visibility:
        value: "public"

    target:
        value: "{{ organization }}\\Yves\\{{ module }}\\{{ module }}DependencyProvider"

preSpryks:
    - AddYvesDependencyProvider
